{{- if .Values.config.secretVariables }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spf-tools.fullname" . }}
  labels:
    {{- include "spf-tools.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := .Values.config.secretVariables }}
  {{ $k | quote }}: {{ $v | b64enc | quote }}
  {{- end }}
{{- end }}